[sophora-server]: add container ports to values.yaml (#108)
subshell/helm-charts pull request #109
Opened 2024-07-11 12:50 UTC by hehu80

2024-07-11 13:43 UTC, tom-schoener requested changes
One minor refactoring of the port reference. When fixed, I'll approve and merge the request.

2024-07-11 13:43 UTC, tom-schoener commented on charts/sophora-server/templates/statefulset.yaml
> +              port: {{ .Values.sophora.server.ports.http }}
I'd rewrite the port as `http` for all probes:

```
port: http
```

2024-07-12 10:35 UTC, hehu80 commented
@tom-schoener can you take another look, we urgently need the change

2024-07-12 11:11 UTC, tom-schoener commented
That is not what I had in mind. Sorry for the confusion. I meant the `port` of the probes in `httpGet`: 

```yaml
livenessProbe:
  httpGet:
    path: /status/liveness
    port: http # <-----
```

The variable name `ports` was fine.

2024-07-12 11:41 UTC, tom-schoener requested changes

2024-07-12 11:41 UTC, tom-schoener commented on charts/sophora-server/templates/statefulset.yaml
> +              port: {{ .Values.sophora.server.port.http }}
```suggestion
              port: http
```

2024-07-12 11:41 UTC, tom-schoener commented on charts/sophora-server/templates/statefulset.yaml
> +              port: {{ .Values.sophora.server.port.http }}
```suggestion
              port: http
```

2024-07-12 11:41 UTC, tom-schoener commented on charts/sophora-server/templates/statefulset.yaml
> +              port: {{ .Values.sophora.server.port.http }}
```suggestion
              port: http
```

2024-07-12 11:48 UTC, hehu80 commented
@tom-schoener can you, again, take another look, we urgently need the change

2024-07-12 11:59 UTC, tom-schoener approved these changes

2024-07-12 11:59 UTC, merged